# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Compatible

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  tests-with-older-go-versions:
    strategy:
      matrix:
        os: [ ubuntu-latest]
        # go: [ '1.17','1.18','1.19','1.20','1.21','1.22','1.23']
        go: [ '1.24' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '${{ matrix.go }}'

    - name: Test
      run: go run ./script/run-test --install-xgo --with-setup --reset-instrument --log-debug -v ./runtime/test/build/modules_with_trap_all/service