# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Next

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  tests-with-go-next:
    # go1.25 to be released 2025-08
    # see https://tip.golang.org/doc/go1.25
    # skip this job until go1.25 is released
    if: false  
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        go: [ '1.25rc1' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      run: |
        curl -fsSL -o go.tar.gz "https://go.dev/dl/go${{matrix.go}}.linux-amd64.tar.gz"
        mkdir setup
        mkdir setup/gopath
        tar -C setup -xzf go.tar.gz
        ls setup
        GOROOT=$PWD/setup/go PATH=$PWD/setup/go/bin:$PATH go version
    
    - name: Test
      run: GOROOT=$PWD/setup/go GOPATH=$PWD/setup/gopath PATH=$PWD/setup/go/bin:$PWD/setup/gopath/bin:$PATH go run ./script/run-test --install-xgo --with-setup --reset-instrument --log-debug -v