# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  tests-with-coverage:
    strategy:
      matrix:
        os: [ ubuntu-latest]
        go: [ '1.24' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '${{ matrix.go }}'

    - name: Test
      run: go run ./script/run-test --install-xgo --reset-instrument --log-debug -v -cover -coverpkg github.com/xhd2015/xgo/runtime/... -coverprofile cover.out

    - name: Merge Coverages
      run: go run ./cmd/go-tool-coverage merge ./cover-*.out -o covermerged-runtime.out --exclude-prefix github.com/xhd2015/xgo/runtime/test --exclude-prefix github.com/xhd2015/xgo/runtime/core/info

    - name: Print coverage
      run: cd runtime && go tool cover --func ../covermerged-runtime.out